require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LibraryInfosController do

  # This should return the minimal set of attributes required to create a valid
  # LibraryInfo. As you add validations to LibraryInfo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LibraryInfosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all library_infos as @library_infos" do
      library_info = LibraryInfo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:library_infos).should eq([library_info])
    end
  end

  describe "GET show" do
    it "assigns the requested library_info as @library_info" do
      library_info = LibraryInfo.create! valid_attributes
      get :show, {:id => library_info.to_param}, valid_session
      assigns(:library_info).should eq(library_info)
    end
  end

  describe "GET new" do
    it "assigns a new library_info as @library_info" do
      get :new, {}, valid_session
      assigns(:library_info).should be_a_new(LibraryInfo)
    end
  end

  describe "GET edit" do
    it "assigns the requested library_info as @library_info" do
      library_info = LibraryInfo.create! valid_attributes
      get :edit, {:id => library_info.to_param}, valid_session
      assigns(:library_info).should eq(library_info)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LibraryInfo" do
        expect {
          post :create, {:library_info => valid_attributes}, valid_session
        }.to change(LibraryInfo, :count).by(1)
      end

      it "assigns a newly created library_info as @library_info" do
        post :create, {:library_info => valid_attributes}, valid_session
        assigns(:library_info).should be_a(LibraryInfo)
        assigns(:library_info).should be_persisted
      end

      it "redirects to the created library_info" do
        post :create, {:library_info => valid_attributes}, valid_session
        response.should redirect_to(LibraryInfo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved library_info as @library_info" do
        # Trigger the behavior that occurs when invalid params are submitted
        LibraryInfo.any_instance.stub(:save).and_return(false)
        post :create, {:library_info => {}}, valid_session
        assigns(:library_info).should be_a_new(LibraryInfo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LibraryInfo.any_instance.stub(:save).and_return(false)
        post :create, {:library_info => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested library_info" do
        library_info = LibraryInfo.create! valid_attributes
        # Assuming there are no other library_infos in the database, this
        # specifies that the LibraryInfo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LibraryInfo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => library_info.to_param, :library_info => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested library_info as @library_info" do
        library_info = LibraryInfo.create! valid_attributes
        put :update, {:id => library_info.to_param, :library_info => valid_attributes}, valid_session
        assigns(:library_info).should eq(library_info)
      end

      it "redirects to the library_info" do
        library_info = LibraryInfo.create! valid_attributes
        put :update, {:id => library_info.to_param, :library_info => valid_attributes}, valid_session
        response.should redirect_to(library_info)
      end
    end

    describe "with invalid params" do
      it "assigns the library_info as @library_info" do
        library_info = LibraryInfo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LibraryInfo.any_instance.stub(:save).and_return(false)
        put :update, {:id => library_info.to_param, :library_info => {}}, valid_session
        assigns(:library_info).should eq(library_info)
      end

      it "re-renders the 'edit' template" do
        library_info = LibraryInfo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LibraryInfo.any_instance.stub(:save).and_return(false)
        put :update, {:id => library_info.to_param, :library_info => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested library_info" do
      library_info = LibraryInfo.create! valid_attributes
      expect {
        delete :destroy, {:id => library_info.to_param}, valid_session
      }.to change(LibraryInfo, :count).by(-1)
    end

    it "redirects to the library_infos list" do
      library_info = LibraryInfo.create! valid_attributes
      delete :destroy, {:id => library_info.to_param}, valid_session
      response.should redirect_to(library_infos_url)
    end
  end

end
